version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: ["nginx", "-g", "daemon off;"]

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server/app:/app
    working_dir: /app 
    command: ["go", "run", "main.go"]